Provide new nonce for wizard
RebelCode/rcmod-wp-bookings-front-ui pull request #22
Opened 2018-09-07 12:09 UTC by romalytvynenko

Implements EDDBK-96

2018-09-10 14:03 UTC, mecha requested changes
The nonce has been added to the REST API module. Kindly make this module depend on the `eddbk_rest_api` module and use the [added nonce][1]. The nonce is stringable, so remember to cast it to a string if needed.

[1]: https://github.com/RebelCode/rcmod-eddbk-rest-api/blob/task/EDDBK-97_auth-create-booking-route/src/Module/EddBkRestApiModule.php#L619

2018-09-10 15:25 UTC, mecha approved these changes

2018-09-11 08:23 UTC, mecha commented
@romalytvynenko Remember to update the changelog!

2018-09-11 11:36 UTC, XedinUnknown approved these changes
I don't like the fact that the Front UI module requires any kind of REST API implementation. The Front UI module is something that should be installed on a client, and should not depend on server-side logic.

However, it was pointed out to me that this is a temporary solution, and therefore it's ok.

2018-09-11 11:36 UTC, merged